name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - namespace-profile-amd64-with-caching
    steps:
      - uses: actions/checkout@v3
      - name: Set up cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: yarn
      - run: yarn
      - run: yarn workspace @project/web-app build
