name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-5gb
      - nscloud-cache-tag-cache-yarn-workspaces-demo-ci
    steps:
      - uses: actions/checkout@v3
      - name: Set up cache
        run: |
          # Cache yarn cache
          yarn_cache=$(yarn cache dir)
          mkdir -p /cache/yarn-cache "$yarn_cache"
          sudo mount --bind /cache/yarn-cache "$yarn_cache"

          # Verify cache size
          du -sh "$yarn_cache"
      - run: yarn
      - run: yarn workspace @project/web-app build
