name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-5gb
      - nscloud-cache-tag-cache-yarn-workspaces-demo-ci
    steps:
      - uses: actions/checkout@v3
      - name: Set up cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: yarn
      - run: yarn
      - run: yarn workspace @project/web-app build
