name: Repro

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runner: [namespace-profile-default, ubuntu-latest]
    runs-on:
      - ${{ matrix.runner }}
    # container:
    #   image: node:20
    #   env:
    #     NODE_ENV: development
    #   options: --cpus 8
    steps:
      - uses: actions/checkout@v3
      - name: Setup timezone
        uses: MathRobin/timezone-action@v1.1
        with:
          timezoneLinux: America/Montreal
      - name: Update timezone
        run: sudo ln -f -s /usr/share/zoneinfo/America/Montreal /etc/localtime
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
      - run: ls -lta ~
      - run: ls -lta ~/.cache
      - run: yarn
      - run: yarn workspace @project/web-app build
