name: Repro

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runner: [namespace-profile-with-caching]
    runs-on:
      - ${{ matrix.runner }}
    # container:
    #   image: node:20
    #   env:
    #     NODE_ENV: development
    #   options: --cpus 8
    steps:
      - uses: actions/checkout@v4
      - uses: namespacelabs/nscloud-cache-action@v1
        with: 
          cache: yarn
          path: node_modules
      - run: yarn version
      - uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"
          always-auth: false
          check-latest: false
      # - name: Setup timezone
      #   uses: MathRobin/timezone-action@v1.1
      #   with:
      #     timezoneLinux: America/Montreal
      # - name: Update timezone
      #   run: sudo ln -f -s /usr/share/zoneinfo/America/Montreal /etc/localtime
      # - name: Setup node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20.11.0
      #     cache: 'yarn'
      #     cache-dependency-path: ./repo/yarn.lock
      # - run: ls -lta ~
      # - run: ls -lta ~/.cache
      # - run: ls -lta ~/.cache/yarn
      # - run: ls -lta ~/.cache/yarn/v6
      # - run: cd repo && yarn
      # - run: cd repo && yarn workspace @project/web-app build
      
