name: Repro

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - namespace-profile-default
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: 'yarn'
      - run: yarn
      - run: yarn workspace @project/web-app build
